# Generated by Django 5.2.1 on 2025-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOCL_Webapp', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
