# Generated by Django 5.2.1 on 2025-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOCL_Webapp', '0004_user_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.TextField(default='Default text', max_length=240),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
