# Generated by Django 5.2.1 on 2025-06-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOCL_Webapp', '0005_user_created_at_user_photo_user_text_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=240)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(max_length=240),
        ),
    ]
