# Generated by Django 5.2.1 on 2025-06-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOCL_Webapp', '0007_remove_product_text_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
