# Generated by Django 5.2.1 on 2025-06-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOCL_Webapp', '0008_product_text_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank='True', default='', max_length=50, null='True'),
        ),
    ]
